<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>md</string>
      <string>chptr</string>
    </array>
    <key>injectionSelector</key>
    <string>meta.paragraph.markdown</string>
    <key>patterns</key>
    <dict>
      <key>chptr-markup</key>
      <dict>
        <key>name</key>
        <string>chptr-markup</string>
        <key>begin</key>
        <string>({)</string>
        <key>end</key>
        <string>(})</string>
        <key>contentName</key>
        <string>markup.italic.markdown</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>markdown.chptr</string>
  </dict>
</plist>